"""API + service tests for repository distillation (AOS-DISTILL-001 / RFC-0008).

Repo content → Knowledge: a scanned repo's README is distilled by a deterministic,
provenance-tagged extractor into ``knowledge/wiki/repositories/<slug>.md`` (repo
vault = source of truth) and projected as a re-syncable ``KnowledgePage``
(``page_type="repository"``). Distillation is idempotent and fails gracefully
(409, not 500) on a non-writable vault without mutating state; a README-less repo
yields a minimal page and never raises.

CRITICAL: every I/O test points ``settings.repository_root`` (via the ``client``
fixture) AND ``settings.knowledge_root`` at ``tmp_path`` — distillation never
reads the real ``repositories/`` nor writes the real ``knowledge/`` vault.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from types import SimpleNamespace

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import types

from aos_core.llm import DeterministicProvider, InstrumentedProvider, OpenAICompatibleProvider
from aos_core.models import KnowledgePage, RepositoryDNA
from aos_core.services.distillation import (
    _repo_slug,
    distill_repository,
    extract_repo_knowledge,
    reason_purpose,
    render_repository_markdown,
    select_source_files,
    summarize_sources,
)

from app.main import settings

UNKNOWN_ID = "00000000-0000-0000-0000-000000000000"

_CODE_FIXTURE = Path(__file__).parent / "fixtures" / "code-repo"

_RICH_README = """\
# Widget Toolkit

A reusable library for building command-line widgets with a small footprint.

## Installation

```bash
pip install widget-toolkit
```

## Usage

```python
from widget import Widget
```

## Contributing

PRs welcome.
"""

_FREE_LLM_README = """\
<!---
WARNING: DO NOT EDIT THIS FILE DIRECTLY.
--->
# Free LLM API resources

This lists various services that provide free access or credits towards API-based LLM usage.

> [!NOTE]
> Please don't abuse these services.

## Free Providers

### OpenRouter

Free tier available.

## Providers with trial credits

### Fireworks

Trial credits on signup.
"""


def _same_file_session(tmp_path):
    engine = create_engine(
        f"sqlite:///{tmp_path / 'test.db'}",
        connect_args={"check_same_thread": False, "timeout": 30},
        pool_pre_ping=True,
    )
    return sessionmaker(bind=engine, autoflush=False, autocommit=False, expire_on_commit=False)()


def _project(client) -> str:
    return client.post("/projects", json={"name": "Distill", "slug": "distill"}).json()["id"]


def _register_repo(client, project_id: str, *, name: str, local_path: str, readme: str | None) -> str:
    """Create a repo dir under the (tmp) repository_root and register it."""
    repo_dir = settings.repository_root / local_path
    repo_dir.mkdir(parents=True, exist_ok=True)
    if readme is not None:
        (repo_dir / "README.md").write_text(readme, encoding="utf-8")
    resp = client.post(
        f"/projects/{project_id}/repositories",
        json={"name": name, "local_path": local_path},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()["id"]


def _register_code_repo(client, project_id: str, *, name: str, local_path: str) -> str:
    """Copy the code-repo fixture under the (tmp) repository_root and register it."""
    repo_dir = settings.repository_root / local_path
    shutil.copytree(_CODE_FIXTURE, repo_dir, dirs_exist_ok=True)
    resp = client.post(
        f"/projects/{project_id}/repositories",
        json={"name": name, "local_path": local_path},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()["id"]


# --- extract_repo_knowledge (pure) -----------------------------------------


def test_extract_repo_knowledge_from_readme() -> None:
    result = extract_repo_knowledge(_RICH_README)

    assert result["title"] == "Widget Toolkit"
    assert result["summary"].startswith("A reusable library for building command-line widgets")
    # Section headings become key points.
    assert any(kp.startswith("Installation") for kp in result["key_points"])
    assert any(kp.startswith("Usage") for kp in result["key_points"])
    # Fenced-code languages are surfaced as technologies.
    assert "python" in [t.lower() for t in result["technologies"]]
    assert "bash" in [t.lower() for t in result["technologies"]]
    # useful_for picks up the "library" / "command-line" signals.
    assert result["useful_for"]
    # Every provenance item cites its source; at least one cites the README.
    assert result["provenance"]
    assert all("source" in entry and "item" in entry for entry in result["provenance"])
    assert any("README.md" in entry["source"] for entry in result["provenance"])


def test_extract_free_llm_style_catalog_names_the_catalog() -> None:
    result = extract_repo_knowledge(_FREE_LLM_README)

    # Title/summary name WHAT IT IS (a catalog), not a structural fingerprint.
    assert result["title"] == "Free LLM API resources"
    assert result["summary"].startswith("This lists various services that provide free access")
    # The catalog / curated-list signal is surfaced under useful_for.
    assert any("catalog" in phrase.lower() or "list" in phrase.lower() for phrase in result["useful_for"])
    # HTML comment + blockquote are not mistaken for the summary.
    assert "DO NOT EDIT" not in result["summary"]
    assert "abuse" not in result["summary"]


_BADGE_FIRST_README = """\
# Gin

[![Build](https://img.example/build.svg)](https://ci.example/build) [![Coverage](https://img.example/cov.svg)](https://cov.example)
![logo](https://img.example/logo.png)

Gin is a high-performance HTTP web framework written in Go, focused on speed and productivity.

## Installation

```bash
go get github.com/gin-gonic/gin
```
"""

_ANALOGY_FIRST_README = """\
# PydanticAI

[![CI](https://img.example/ci.svg)](https://ci.example)

FastAPI revolutionized web development with an ergonomic design and type hints. PydanticAI is a Python agent framework with tool calling and structured outputs.
"""

_ALL_BADGE_README = """\
# Shiny

[![Build](https://img.example/build.svg)](https://ci.example/build)
![logo](https://img.example/logo.png)
[![Coverage](https://img.example/cov.svg)](https://cov.example)
"""


def test_summary_floor_skips_badges_for_the_real_description() -> None:
    result = extract_repo_knowledge(_BADGE_FIRST_README, name="gin")

    # The declarative description sentence is chosen, not the badge/image markup.
    assert result["summary"].startswith("Gin is a high-performance HTTP web framework")
    # No badge / image / link markup ever leaks into the summary.
    assert "![" not in result["summary"]
    assert "](" not in result["summary"]
    assert "https://" not in result["summary"]


def test_summary_floor_prefers_declarative_sentence_over_analogy() -> None:
    # The lead sentence is an analogy about *FastAPI*; the description is the
    # following "<Name> is a …" sentence. The floor must pick the latter.
    result = extract_repo_knowledge(_ANALOGY_FIRST_README, name="PydanticAI")

    assert result["summary"].startswith("PydanticAI is a Python agent framework")
    assert "FastAPI" not in result["summary"]
    assert "revolutionized" not in result["summary"]


def test_summary_floor_never_emits_badge_only_markup() -> None:
    # An all-badge / no-prose README yields the honest fallback, never markup.
    result = extract_repo_knowledge(_ALL_BADGE_README, name="shiny")

    assert result["summary"] == "README present but no prose summary could be extracted."
    assert "![" not in result["summary"]
    assert "[!" not in result["summary"]


def test_extract_empty_readme_is_minimal_and_never_raises() -> None:
    result = extract_repo_knowledge("   \n\n")
    assert result["title"] == "Untitled repository"
    assert "No README content" in result["summary"]
    assert result["key_points"] == []
    assert result["technologies"] == []


def test_render_repository_markdown_has_all_sections() -> None:
    md = render_repository_markdown(extract_repo_knowledge(_RICH_README))
    assert "# Widget Toolkit" in md
    assert "## Summary" in md
    assert "## What it is / useful for" in md
    assert "## Key points" in md
    assert "## Technologies" in md
    assert "## Provenance" in md


def test_repo_slug() -> None:
    assert _repo_slug("free-llm-api-resources") == "free-llm-api-resources"
    assert _repo_slug("My Cool Repo!") == "my-cool-repo"
    assert _repo_slug("") == "repository"


# --- distill_repository (I/O + KnowledgePage projection) --------------------


def test_distill_writes_page_and_sets_dna_purpose(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Free LLM API Resources", local_path="free-llm", readme=_FREE_LLM_README
    )

    # Seed a DNA row so distillation can enrich technologies + stamp purpose.
    session = _same_file_session(tmp_path)
    try:
        session.add(
            RepositoryDNA(
                repository_id=repo_id,
                package_managers=["pip"],
                scan_summary={"summary": {"language_classes": {"Python": "source", "Markdown": "docs"}}},
            )
        )
        session.commit()
    finally:
        session.close()

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()
    assert page["page_type"] == "repository"
    assert page["validation_state"] == "derived"
    assert page["vault_path"] == "wiki/repositories/free-llm-api-resources.md"
    assert page["title"] == "Free LLM API resources"
    ref_types = {ref["type"] for ref in page["source_refs"]}
    assert "repository" in ref_types and "vault_file" in ref_types

    written = tmp_path / page["vault_path"]
    assert written.is_file()
    text = written.read_text(encoding="utf-8")
    assert "# Free LLM API resources" in text
    assert "This lists various services" in text
    assert "pip" in text  # DNA package manager surfaced as a technology
    assert "Python" in text  # DNA source language surfaced

    # DNA.purpose stamped with the distilled summary.
    session = _same_file_session(tmp_path)
    try:
        dna = session.query(RepositoryDNA).filter(RepositoryDNA.repository_id == repo_id).one()
        assert dna.purpose.startswith("This lists various services")
    finally:
        session.close()

    # Projected page is queryable and typed.
    pages = client.get("/knowledge/pages", params={"page_type": "repository"}).json()
    assert page["id"] in [p["id"] for p in pages]


def test_distill_is_idempotent(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README)

    first = client.post(f"/repositories/{repo_id}/distill")
    second = client.post(f"/repositories/{repo_id}/distill")
    assert first.status_code == 200 and second.status_code == 200, second.text
    assert first.json()["vault_path"] == second.json()["vault_path"]
    assert first.json()["id"] == second.json()["id"]

    # One file, one page.
    matches = list((tmp_path / "wiki" / "repositories").glob("*.md"))
    assert len(matches) == 1
    session = _same_file_session(tmp_path)
    try:
        assert (
            session.query(KnowledgePage)
            .filter(KnowledgePage.vault_path == "wiki/repositories/widget-toolkit.md")
            .count()
            == 1
        )
    finally:
        session.close()


def test_distill_non_writable_vault_is_409_without_mutating_state(client, tmp_path) -> None:
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README)

    # Point knowledge_root at a *file*, so mkdir under it raises OSError.
    bad_root = tmp_path / "not-a-dir"
    bad_root.write_text("x", encoding="utf-8")
    settings.knowledge_root = bad_root

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 409, resp.text
    assert "local-first" in resp.json()["detail"].lower()

    # No KnowledgePage was created (state untouched).
    session = _same_file_session(tmp_path)
    try:
        assert session.query(KnowledgePage).filter(KnowledgePage.page_type == "repository").count() == 0
    finally:
        session.close()


def test_distill_readme_less_repo_is_minimal_and_no_raise(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Empty Repo", local_path="empty", readme=None)

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()
    assert page["page_type"] == "repository"
    # No README → title falls back to the registered repo name.
    assert page["title"] == "Empty Repo"

    text = (tmp_path / page["vault_path"]).read_text(encoding="utf-8")
    assert "# Empty Repo" in text
    assert "No README content" in text


def test_distill_missing_repository_is_404(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    assert client.post(f"/repositories/{UNKNOWN_ID}/distill").status_code == 404


# --- Phase 2 (RFC-0008): code-aware distillation ----------------------------


def test_select_source_files_picks_entry_points_modules_manifest(client, tmp_path) -> None:
    # Copy the code fixture under the (tmp) repository_root; settings.repository_root
    # is pinned by the client fixture and read via get_settings() inside the selector.
    shutil.copytree(_CODE_FIXTURE, settings.repository_root / "code-repo", dirs_exist_ok=True)
    repository = SimpleNamespace(local_path="code-repo")

    files = select_source_files(repository)
    by_path = {f["path"]: f for f in files}

    assert "app.py" in by_path
    assert "core.py" in by_path
    assert "pyproject.toml" in by_path
    # app.py reads as an entry point (app.* stem); core.py is a plain module.
    assert by_path["app.py"]["is_entry_point"] is True
    assert by_path["app.py"]["role"] == "entry_point"
    assert by_path["core.py"]["is_entry_point"] is False
    assert by_path["core.py"]["role"] == "module"
    assert by_path["pyproject.toml"]["role"] == "manifest"
    # Content is carried (needed by the summarizer / narrative).
    assert "class Engine" in by_path["core.py"]["text"]

    # cap_files is honoured — the entry point is selected first.
    capped = select_source_files(repository, cap_files=1)
    assert len(capped) == 1
    assert capped[0]["path"] == "app.py"

    # A running byte cap is honoured (0 budget → nothing selected).
    assert select_source_files(repository, cap_bytes=0) == []


def test_select_source_files_is_tolerant_of_missing_repo(client, tmp_path) -> None:
    # A repo path that does not exist under repository_root → [], never raises.
    assert select_source_files(SimpleNamespace(local_path="does-not-exist")) == []


def test_summarize_sources_extracts_docstring_and_symbols(client, tmp_path) -> None:
    shutil.copytree(_CODE_FIXTURE, settings.repository_root / "code-repo", dirs_exist_ok=True)
    files = select_source_files(SimpleNamespace(local_path="code-repo"))

    summary = summarize_sources(files)
    components = {c["path"]: c for c in summary["components"]}

    app = components["app.py"]
    assert app["docstring"].startswith("Entry point for the sample app")
    assert "run" in app["symbols"]
    assert "App" in app["symbols"]
    assert app["provenance"] == "app.py"

    core = components["core.py"]
    assert "Engine" in core["symbols"]
    assert "build_default" in core["symbols"]

    # app.py is reported as an entry point.
    assert "app.py" in summary["entry_points"]


def test_distill_code_repo_renders_components_section(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_code_repo(client, project_id, name="Code Repo", local_path="code-repo")

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()

    text = (tmp_path / page["vault_path"]).read_text(encoding="utf-8")
    # The deterministic Components section names the entry point + module, per-file.
    assert "## Components (from source)" in text
    assert "`app.py`" in text
    assert "`core.py`" in text
    # Source files read are recorded in Provenance.
    assert "source file read — source: app.py" in text
    # The deterministic provider fabricates NO narrative.
    assert "## How it works / Built for" not in text


# --- AOS-DISTILL-004: reasoned DNA.purpose tier (hermetic — NO live model) ---
#
# The real-provider path is exercised with a FAKE provider stub whose ``.name`` is
# NOT "deterministic" and whose ``.generate`` returns canned JSON. No ``claude``
# binary is ever shelled: these tests prove the derived/reasoned branching + the
# fabrication-free fallback purely in-process.

_REASONED_PURPOSE = (
    "Widget Toolkit is a lightweight library for composing terminal UI widgets, "
    "useful for building small command-line dashboards."
)


class _FakeReasonedProvider:
    """A fake NON-deterministic provider returning canned reasoned JSON (no live model).

    ``.name != "deterministic"`` selects the reasoned tier; ``.generate`` records
    each call so a test can assert the provider was actually invoked (the gating
    let the real-provider path run) and returns a ``purpose`` sentence.
    """

    name = "claude_code"

    def __init__(self, purpose: str = _REASONED_PURPOSE) -> None:
        self._purpose = purpose
        self.calls: list[dict] = []

    def generate(self, *, system: str, prompt: str, max_tokens: int = 1024):
        self.calls.append({"system": system, "prompt": prompt})
        return SimpleNamespace(
            text=json.dumps({"purpose": self._purpose}),
            provider=self.name,
            model=None,
            finish_reason="stop",
        )


class _FakeGarbledProvider:
    """A fake real provider whose output has no usable purpose (empty / non-JSON)."""

    name = "claude_code"

    def __init__(self, text: str) -> None:
        self._text = text
        self.calls: list[dict] = []

    def generate(self, *, system: str, prompt: str, max_tokens: int = 1024):
        self.calls.append({"system": system, "prompt": prompt})
        return SimpleNamespace(text=self._text, provider=self.name, model=None, finish_reason="stop")


def _seed_dna(tmp_path, repo_id: str) -> None:
    session = _same_file_session(tmp_path)
    try:
        session.add(
            RepositoryDNA(
                repository_id=repo_id,
                package_managers=["pip"],
                scan_summary={"summary": {"language_classes": {"Python": "source"}}},
            )
        )
        session.commit()
    finally:
        session.close()


def _dna_purpose(tmp_path, repo_id: str) -> str:
    session = _same_file_session(tmp_path)
    try:
        return session.query(RepositoryDNA).filter(RepositoryDNA.repository_id == repo_id).one().purpose
    finally:
        session.close()


def test_reason_purpose_gating_and_parsing_is_hermetic(monkeypatch) -> None:
    """reason_purpose now calls verified_generate internally; test via route monkeypatch."""
    import aos_core.services.verifier as verifier_mod
    from aos_core.services.llm_router import RouteResult, Tier

    files = [{"path": "app.py", "text": "print('hi')"}]
    det_settings = types.SimpleNamespace(llm_provider="deterministic")

    # Deterministic tier is gated OUT — verified_generate short-circuits → "".
    def _det_route(task_class, sensitivity, s):
        return RouteResult(tier=Tier.DETERMINISTIC, provider=DeterministicProvider(), reason="test")

    monkeypatch.setattr(verifier_mod, "route", _det_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)
    assert reason_purpose(_RICH_README, files, det_settings) == ""

    # A real (FREE_HOSTED) provider returning a canned purpose yields that exact sentence.
    good = _FakeReasonedProvider("Repo X is a tool useful for Y.")

    def _real_route(task_class, sensitivity, s):
        return RouteResult(tier=Tier.FREE_HOSTED, provider=good, reason="test")

    monkeypatch.setattr(verifier_mod, "route", _real_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)  # skip verify pass
    assert reason_purpose(_RICH_README, files, det_settings) == "Repo X is a tool useful for Y."
    assert good.calls  # the real-provider path actually ran

    # Empty / garbled / purpose-less real output → "" (no fabrication).
    for bad_text in ("", "not json at all", '{"other": "x"}', '{"purpose": "   "}'):
        garbled = _FakeGarbledProvider(bad_text)
        monkeypatch.setattr(verifier_mod, "route", lambda tc, s, st, _p=garbled: RouteResult(tier=Tier.FREE_HOSTED, provider=_p, reason="test"))
        assert reason_purpose(_RICH_README, files, det_settings) == ""


def _patch_route_free_hosted(monkeypatch, provider) -> None:
    """Patch both the verifier and distillation modules to route to a fake FREE_HOSTED provider.

    Two patches are required:
    - ``verifier_mod.route``: controls which provider ``verified_generate`` uses internally.
    - ``distillation_mod.route``: controls the ``real`` flag in ``distill_repository`` so the
      reasoned branch is entered (Tier != DETERMINISTIC).
    ``verifier_mod._available`` is set to ``False`` so the Claude adversarial pass is skipped
    (the fake's output is accepted as-is; end-to-end refutation is tested in test_verifier.py).
    """
    import aos_core.services.distillation as distillation_mod
    import aos_core.services.verifier as verifier_mod
    from aos_core.services.llm_router import RouteResult, Tier

    fake_route = lambda tc, sens, s: RouteResult(  # noqa: E731
        tier=Tier.FREE_HOSTED, provider=provider, reason="test"
    )
    monkeypatch.setattr(verifier_mod, "route", fake_route)
    monkeypatch.setattr(distillation_mod, "route", fake_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)


def test_distill_reasoned_provider_sets_reasoned_purpose_and_state(client, tmp_path, monkeypatch) -> None:
    """verified_generate production path: a FREE_HOSTED fake returns a reasoned purpose."""
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README
    )
    _seed_dna(tmp_path, repo_id)

    provider = _FakeReasonedProvider()
    _patch_route_free_hosted(monkeypatch, provider)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(
            session, repository_id=repo_id, knowledge_root=tmp_path
        )
        assert page.validation_state == "reasoned"
    finally:
        session.close()

    # The production verified_generate path invoked the fake provider.
    assert provider.calls
    # DNA.purpose IS the reasoned line, not the deterministic floor summary.
    purpose = _dna_purpose(tmp_path, repo_id)
    assert purpose == _REASONED_PURPOSE
    assert not purpose.startswith("A reusable library for building command-line widgets")

    # Single source of truth: the rendered page summary reflects the reasoned line.
    text = (tmp_path / page.vault_path).read_text(encoding="utf-8")
    assert _REASONED_PURPOSE in text


def test_distill_deterministic_provider_keeps_floor_and_derived(client, tmp_path, monkeypatch) -> None:
    """DETERMINISTIC route: verified_generate short-circuits; floor summary kept.

    No monkeypatching of route needed: ``get_settings().llm_provider`` defaults to
    ``"deterministic"`` in the test environment, so ``route()`` returns DETERMINISTIC
    already, and ``real`` is False. The test confirms this inherited CI default holds.
    """
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README
    )
    _seed_dna(tmp_path, repo_id)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(
            session, repository_id=repo_id, knowledge_root=tmp_path
        )
        assert page.validation_state == "derived"
    finally:
        session.close()

    # DNA.purpose is the deterministic floor summary (hermetic, no live model).
    purpose = _dna_purpose(tmp_path, repo_id)
    assert purpose.startswith("A reusable library for building command-line widgets")


def test_distill_garbled_reasoned_output_falls_back_to_floor(client, tmp_path, monkeypatch) -> None:
    """FREE_HOSTED fake returns garbled JSON: verified_generate path runs but yields no purpose."""
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README
    )
    _seed_dna(tmp_path, repo_id)

    # A real (non-deterministic) provider whose output has no usable purpose.
    provider = _FakeGarbledProvider('{"purpose": ""}')
    _patch_route_free_hosted(monkeypatch, provider)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(
            session, repository_id=repo_id, knowledge_root=tmp_path
        )
        assert page.validation_state == "derived"
    finally:
        session.close()

    assert provider.calls  # the production path ran, but produced no usable purpose
    purpose = _dna_purpose(tmp_path, repo_id)
    # No fabrication: the deterministic floor summary is preserved.
    assert purpose.startswith("A reusable library for building command-line widgets")


# --- AOS-LLM-ROUTE-COV: distillation service uses routed_provider ---


def _route_settings(**over):
    """Minimal hermetic settings for router-selection assertions."""
    base = dict(
        llm_base_url="http://localhost:11434/v1",
        llm_model="qwen2.5-coder:7b",
        llm_api_key="",
        llm_free_base_url="https://api.groq.com/openai/v1",
        llm_free_model="llama-3.3-70b-versatile",
        llm_free_api_key="gsk_test",
        llm_claude_enabled=False,
    )
    base.update(over)
    return types.SimpleNamespace(**base)


def test_distillation_routes_to_free_tier_when_local_absent(monkeypatch):
    """When LOCAL is unconfigured and a free key exists, distillation picks FREE_HOSTED."""
    import aos_core.services.llm_router as router_mod

    # No rotation pool (slice 3) so the single-key path is exercised.
    monkeypatch.setattr(router_mod, "build_free_pool", lambda: [])
    monkeypatch.setattr(router_mod, "free_pool_provider", lambda: None)

    from aos_core.services.llm_router import Sensitivity, routed_provider

    s = _route_settings(llm_base_url="", llm_model="")
    provider = routed_provider("distillation", Sensitivity.PUBLIC, s)
    assert isinstance(provider, OpenAICompatibleProvider)


def test_distillation_falls_back_deterministic_when_nothing_configured(monkeypatch):
    """With no tier configured, distillation falls back to deterministic (hermetic CI)."""
    import aos_core.services.llm_router as router_mod

    monkeypatch.setattr(router_mod, "build_free_pool", lambda: [])
    monkeypatch.setattr(router_mod, "free_pool_provider", lambda: None)

    from aos_core.services.llm_router import Sensitivity, routed_provider

    s = _route_settings(llm_base_url="", llm_model="", llm_free_api_key="")
    provider = routed_provider("distillation", Sensitivity.PUBLIC, s)
    assert isinstance(provider, DeterministicProvider)
    # is_real_provider check in distill_repository must still read "deterministic"
    assert getattr(provider, "name", "") == "deterministic"


def test_distillation_wraps_in_instrumented_when_sink_supplied(monkeypatch):
    """With a FREE tier configured + sink, routed_provider wraps in InstrumentedProvider."""
    import aos_core.services.llm_router as router_mod

    monkeypatch.setattr(router_mod, "build_free_pool", lambda: [])
    monkeypatch.setattr(router_mod, "free_pool_provider", lambda: None)

    from aos_core.services.llm_router import Sensitivity, routed_provider

    s = _route_settings(llm_base_url="", llm_model="")
    sink_calls: list = []
    provider = routed_provider("distillation", Sensitivity.PUBLIC, s, sink=lambda **kw: sink_calls.append(kw))
    assert isinstance(provider, InstrumentedProvider)
    assert isinstance(provider.inner, OpenAICompatibleProvider)
