"""API + service tests for repository distillation (AOS-DISTILL-001 / RFC-0008).

Repo content → Knowledge: a scanned repo's README is distilled by a deterministic,
provenance-tagged extractor into ``knowledge/wiki/repositories/<slug>.md`` (repo
vault = source of truth) and projected as a re-syncable ``KnowledgePage``
(``page_type="repository"``). Distillation is idempotent and fails gracefully
(409, not 500) on a non-writable vault without mutating state; a README-less repo
yields a minimal page and never raises.

CRITICAL: every I/O test points ``settings.repository_root`` (via the ``client``
fixture) AND ``settings.knowledge_root`` at ``tmp_path`` — distillation never
reads the real ``repositories/`` nor writes the real ``knowledge/`` vault.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from types import SimpleNamespace

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import types

from aos_core.llm import DeterministicProvider, InstrumentedProvider, OpenAICompatibleProvider
from aos_core.models import KnowledgePage, RepositoryDNA
import logging

from aos_core.services.distillation import (
    _bounded_reason_body,
    _drop_uncited_capabilities,
    _REASON_PROMPT_CHAR_BUDGET,
    _repo_slug,
    build_repo_digest,
    distill_repository,
    extract_repo_knowledge,
    reason_over_source,
    reason_purpose,
    render_repository_markdown,
    select_source_files,
    summarize_sources,
)

from app.main import settings

UNKNOWN_ID = "00000000-0000-0000-0000-000000000000"

_CODE_FIXTURE = Path(__file__).parent / "fixtures" / "code-repo"

_RICH_README = """\
# Widget Toolkit

A reusable library for building command-line widgets with a small footprint.

## Installation

```bash
pip install widget-toolkit
```

## Usage

```python
from widget import Widget
```

## Contributing

PRs welcome.
"""

_FREE_LLM_README = """\
<!---
WARNING: DO NOT EDIT THIS FILE DIRECTLY.
--->
# Free LLM API resources

This lists various services that provide free access or credits towards API-based LLM usage.

> [!NOTE]
> Please don't abuse these services.

## Free Providers

### OpenRouter

Free tier available.

## Providers with trial credits

### Fireworks

Trial credits on signup.
"""


def _same_file_session(tmp_path):
    engine = create_engine(
        f"sqlite:///{tmp_path / 'test.db'}",
        connect_args={"check_same_thread": False, "timeout": 30},
        pool_pre_ping=True,
    )
    return sessionmaker(bind=engine, autoflush=False, autocommit=False, expire_on_commit=False)()


def _project(client) -> str:
    return client.post("/projects", json={"name": "Distill", "slug": "distill"}).json()["id"]


def _register_repo(client, project_id: str, *, name: str, local_path: str, readme: str | None) -> str:
    """Create a repo dir under the (tmp) repository_root and register it."""
    repo_dir = settings.repository_root / local_path
    repo_dir.mkdir(parents=True, exist_ok=True)
    if readme is not None:
        (repo_dir / "README.md").write_text(readme, encoding="utf-8")
    resp = client.post(
        f"/projects/{project_id}/repositories",
        json={"name": name, "local_path": local_path},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()["id"]


def _write_repo(root, files: dict) -> str:
    """Write a synthetic repo tree under settings.repository_root; return its local_path."""
    base = root / "synthetic"
    for rel, content in files.items():
        target = base / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return "synthetic"


def _register_code_repo(client, project_id: str, *, name: str, local_path: str) -> str:
    """Copy the code-repo fixture under the (tmp) repository_root and register it."""
    repo_dir = settings.repository_root / local_path
    shutil.copytree(_CODE_FIXTURE, repo_dir, dirs_exist_ok=True)
    resp = client.post(
        f"/projects/{project_id}/repositories",
        json={"name": name, "local_path": local_path},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()["id"]


# --- extract_repo_knowledge (pure) -----------------------------------------


def test_extract_repo_knowledge_from_readme() -> None:
    result = extract_repo_knowledge(_RICH_README)

    assert result["title"] == "Widget Toolkit"
    assert result["summary"].startswith("A reusable library for building command-line widgets")
    # Section headings become key points.
    assert any(kp.startswith("Installation") for kp in result["key_points"])
    assert any(kp.startswith("Usage") for kp in result["key_points"])
    # Fenced-code languages are surfaced as technologies.
    assert "python" in [t.lower() for t in result["technologies"]]
    assert "bash" in [t.lower() for t in result["technologies"]]
    # useful_for picks up the "library" / "command-line" signals.
    assert result["useful_for"]
    # Every provenance item cites its source; at least one cites the README.
    assert result["provenance"]
    assert all("source" in entry and "item" in entry for entry in result["provenance"])
    assert any("README.md" in entry["source"] for entry in result["provenance"])


def test_extract_free_llm_style_catalog_names_the_catalog() -> None:
    result = extract_repo_knowledge(_FREE_LLM_README)

    # Title/summary name WHAT IT IS (a catalog), not a structural fingerprint.
    assert result["title"] == "Free LLM API resources"
    assert result["summary"].startswith("This lists various services that provide free access")
    # The catalog / curated-list signal is surfaced under useful_for.
    assert any("catalog" in phrase.lower() or "list" in phrase.lower() for phrase in result["useful_for"])
    # HTML comment + blockquote are not mistaken for the summary.
    assert "DO NOT EDIT" not in result["summary"]
    assert "abuse" not in result["summary"]


_BADGE_FIRST_README = """\
# Gin

[![Build](https://img.example/build.svg)](https://ci.example/build) [![Coverage](https://img.example/cov.svg)](https://cov.example)
![logo](https://img.example/logo.png)

Gin is a high-performance HTTP web framework written in Go, focused on speed and productivity.

## Installation

```bash
go get github.com/gin-gonic/gin
```
"""

_ANALOGY_FIRST_README = """\
# PydanticAI

[![CI](https://img.example/ci.svg)](https://ci.example)

FastAPI revolutionized web development with an ergonomic design and type hints. PydanticAI is a Python agent framework with tool calling and structured outputs.
"""

_ALL_BADGE_README = """\
# Shiny

[![Build](https://img.example/build.svg)](https://ci.example/build)
![logo](https://img.example/logo.png)
[![Coverage](https://img.example/cov.svg)](https://cov.example)
"""


def test_summary_floor_skips_badges_for_the_real_description() -> None:
    result = extract_repo_knowledge(_BADGE_FIRST_README, name="gin")

    # The declarative description sentence is chosen, not the badge/image markup.
    assert result["summary"].startswith("Gin is a high-performance HTTP web framework")
    # No badge / image / link markup ever leaks into the summary.
    assert "![" not in result["summary"]
    assert "](" not in result["summary"]
    assert "https://" not in result["summary"]


def test_summary_floor_prefers_declarative_sentence_over_analogy() -> None:
    # The lead sentence is an analogy about *FastAPI*; the description is the
    # following "<Name> is a …" sentence. The floor must pick the latter.
    result = extract_repo_knowledge(_ANALOGY_FIRST_README, name="PydanticAI")

    assert result["summary"].startswith("PydanticAI is a Python agent framework")
    assert "FastAPI" not in result["summary"]
    assert "revolutionized" not in result["summary"]


def test_summary_floor_never_emits_badge_only_markup() -> None:
    # An all-badge / no-prose README yields the honest fallback, never markup.
    result = extract_repo_knowledge(_ALL_BADGE_README, name="shiny")

    assert result["summary"] == "README present but no prose summary could be extracted."
    assert "![" not in result["summary"]
    assert "[!" not in result["summary"]


def test_extract_empty_readme_is_minimal_and_never_raises() -> None:
    result = extract_repo_knowledge("   \n\n")
    assert result["title"] == "Untitled repository"
    assert "No README content" in result["summary"]
    assert result["key_points"] == []
    assert result["technologies"] == []


def test_render_repository_markdown_has_all_sections() -> None:
    md = render_repository_markdown(extract_repo_knowledge(_RICH_README))
    assert "# Widget Toolkit" in md
    assert "## Summary" in md
    assert "## What it is / useful for" in md
    assert "## Key points" in md
    assert "## Technologies" in md
    assert "## Provenance" in md


def test_repo_slug() -> None:
    assert _repo_slug("free-llm-api-resources") == "free-llm-api-resources"
    assert _repo_slug("My Cool Repo!") == "my-cool-repo"
    assert _repo_slug("") == "repository"


# --- distill_repository (I/O + KnowledgePage projection) --------------------


def test_distill_writes_page_and_sets_dna_purpose(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Free LLM API Resources", local_path="free-llm", readme=_FREE_LLM_README
    )

    # Seed a DNA row so distillation can enrich technologies + stamp purpose.
    session = _same_file_session(tmp_path)
    try:
        session.add(
            RepositoryDNA(
                repository_id=repo_id,
                package_managers=["pip"],
                scan_summary={"summary": {"language_classes": {"Python": "source", "Markdown": "docs"}}},
            )
        )
        session.commit()
    finally:
        session.close()

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()
    assert page["page_type"] == "repository"
    assert page["validation_state"] == "derived"
    assert page["vault_path"] == "wiki/repositories/free-llm-api-resources.md"
    assert page["title"] == "Free LLM API resources"
    ref_types = {ref["type"] for ref in page["source_refs"]}
    assert "repository" in ref_types and "vault_file" in ref_types

    written = tmp_path / page["vault_path"]
    assert written.is_file()
    text = written.read_text(encoding="utf-8")
    assert "# Free LLM API resources" in text
    assert "This lists various services" in text
    assert "pip" in text  # DNA package manager surfaced as a technology
    assert "Python" in text  # DNA source language surfaced

    # DNA.purpose stamped with the distilled summary.
    session = _same_file_session(tmp_path)
    try:
        dna = session.query(RepositoryDNA).filter(RepositoryDNA.repository_id == repo_id).one()
        assert dna.purpose.startswith("This lists various services")
    finally:
        session.close()

    # Projected page is queryable and typed.
    pages = client.get("/knowledge/pages", params={"page_type": "repository"}).json()
    assert page["id"] in [p["id"] for p in pages]


def test_distill_is_idempotent(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README)

    first = client.post(f"/repositories/{repo_id}/distill")
    second = client.post(f"/repositories/{repo_id}/distill")
    assert first.status_code == 200 and second.status_code == 200, second.text
    assert first.json()["vault_path"] == second.json()["vault_path"]
    assert first.json()["id"] == second.json()["id"]

    # One file, one page.
    matches = list((tmp_path / "wiki" / "repositories").glob("*.md"))
    assert len(matches) == 1
    session = _same_file_session(tmp_path)
    try:
        assert (
            session.query(KnowledgePage)
            .filter(KnowledgePage.vault_path == "wiki/repositories/widget-toolkit.md")
            .count()
            == 1
        )
    finally:
        session.close()


def test_distill_non_writable_vault_is_409_without_mutating_state(client, tmp_path) -> None:
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README)

    # Point knowledge_root at a *file*, so mkdir under it raises OSError.
    bad_root = tmp_path / "not-a-dir"
    bad_root.write_text("x", encoding="utf-8")
    settings.knowledge_root = bad_root

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 409, resp.text
    assert "local-first" in resp.json()["detail"].lower()

    # No KnowledgePage was created (state untouched).
    session = _same_file_session(tmp_path)
    try:
        assert session.query(KnowledgePage).filter(KnowledgePage.page_type == "repository").count() == 0
    finally:
        session.close()


def test_distill_readme_less_repo_is_minimal_and_no_raise(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Empty Repo", local_path="empty", readme=None)

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()
    assert page["page_type"] == "repository"
    # No README → title falls back to the registered repo name.
    assert page["title"] == "Empty Repo"

    text = (tmp_path / page["vault_path"]).read_text(encoding="utf-8")
    assert "# Empty Repo" in text
    assert "No README content" in text


def test_distill_missing_repository_is_404(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    assert client.post(f"/repositories/{UNKNOWN_ID}/distill").status_code == 404


# --- Phase 2 (RFC-0008): code-aware distillation ----------------------------


def test_select_source_files_picks_entry_points_modules_manifest(client, tmp_path) -> None:
    # Copy the code fixture under the (tmp) repository_root; settings.repository_root
    # is pinned by the client fixture and read via get_settings() inside the selector.
    shutil.copytree(_CODE_FIXTURE, settings.repository_root / "code-repo", dirs_exist_ok=True)
    repository = SimpleNamespace(local_path="code-repo")

    files = select_source_files(repository)
    by_path = {f["path"]: f for f in files}

    assert "app.py" in by_path
    assert "core.py" in by_path
    assert "pyproject.toml" in by_path
    # app.py reads as an entry point (app.* stem); core.py is a plain module.
    assert by_path["app.py"]["is_entry_point"] is True
    assert by_path["app.py"]["role"] == "entry_point"
    assert by_path["core.py"]["is_entry_point"] is False
    assert by_path["core.py"]["role"] == "module"
    assert by_path["pyproject.toml"]["role"] == "manifest"
    # Content is carried (needed by the summarizer / narrative).
    assert "class Engine" in by_path["core.py"]["text"]

    # cap_files is honoured — the entry point is selected first.
    capped = select_source_files(repository, cap_files=1)
    assert len(capped) == 1
    assert capped[0]["path"] == "app.py"

    # A running byte cap is honoured (0 budget → nothing selected).
    assert select_source_files(repository, cap_bytes=0) == []


def test_select_source_files_is_tolerant_of_missing_repo(client, tmp_path) -> None:
    # A repo path that does not exist under repository_root → [], never raises.
    assert select_source_files(SimpleNamespace(local_path="does-not-exist")) == []


def test_summarize_sources_extracts_docstring_and_symbols(client, tmp_path) -> None:
    shutil.copytree(_CODE_FIXTURE, settings.repository_root / "code-repo", dirs_exist_ok=True)
    files = select_source_files(SimpleNamespace(local_path="code-repo"))

    summary = summarize_sources(files)
    components = {c["path"]: c for c in summary["components"]}

    app = components["app.py"]
    assert app["docstring"].startswith("Entry point for the sample app")
    assert "run" in app["symbols"]
    assert "App" in app["symbols"]
    assert app["provenance"] == "app.py"

    core = components["core.py"]
    assert "Engine" in core["symbols"]
    assert "build_default" in core["symbols"]

    # app.py is reported as an entry point.
    assert "app.py" in summary["entry_points"]


def test_distill_code_repo_renders_components_section(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_code_repo(client, project_id, name="Code Repo", local_path="code-repo")

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()

    text = (tmp_path / page["vault_path"]).read_text(encoding="utf-8")
    # The deterministic Components section names the entry point + module, per-file.
    assert "## Components (from source)" in text
    assert "`app.py`" in text
    assert "`core.py`" in text
    # Source files read are recorded in Provenance.
    assert "source file read — source: app.py" in text
    # The deterministic provider fabricates NO narrative.
    assert "## How it works / Built for" not in text


# --- AOS-DISTILL-004: reasoned DNA.purpose tier (hermetic — NO live model) ---
#
# The real-provider path is exercised with a FAKE provider stub whose ``.name`` is
# NOT "deterministic" and whose ``.generate`` returns canned JSON. No ``claude``
# binary is ever shelled: these tests prove the derived/reasoned branching + the
# fabrication-free fallback purely in-process.

_REASONED_PURPOSE = (
    "Widget Toolkit is a lightweight library for composing terminal UI widgets, "
    "useful for building small command-line dashboards."
)


class _FakeReasonedProvider:
    """A fake NON-deterministic provider returning canned reasoned JSON (no live model).

    ``.name != "deterministic"`` selects the reasoned tier; ``.generate`` records
    each call so a test can assert the provider was actually invoked (the gating
    let the real-provider path run) and returns a ``purpose`` sentence.
    """

    name = "claude_code"

    def __init__(self, purpose: str = _REASONED_PURPOSE) -> None:
        self._purpose = purpose
        self.calls: list[dict] = []

    def generate(self, *, system: str, prompt: str, max_tokens: int = 1024):
        self.calls.append({"system": system, "prompt": prompt})
        return SimpleNamespace(
            text=json.dumps({"purpose": self._purpose}),
            provider=self.name,
            model=None,
            finish_reason="stop",
        )


class _FakeGarbledProvider:
    """A fake real provider whose output has no usable purpose (empty / non-JSON)."""

    name = "claude_code"

    def __init__(self, text: str) -> None:
        self._text = text
        self.calls: list[dict] = []

    def generate(self, *, system: str, prompt: str, max_tokens: int = 1024):
        self.calls.append({"system": system, "prompt": prompt})
        return SimpleNamespace(text=self._text, provider=self.name, model=None, finish_reason="stop")


def _seed_dna(tmp_path, repo_id: str) -> None:
    session = _same_file_session(tmp_path)
    try:
        session.add(
            RepositoryDNA(
                repository_id=repo_id,
                package_managers=["pip"],
                scan_summary={"summary": {"language_classes": {"Python": "source"}}},
            )
        )
        session.commit()
    finally:
        session.close()


def _dna_purpose(tmp_path, repo_id: str) -> str:
    session = _same_file_session(tmp_path)
    try:
        return session.query(RepositoryDNA).filter(RepositoryDNA.repository_id == repo_id).one().purpose
    finally:
        session.close()


def test_reason_purpose_gating_and_parsing_is_hermetic(monkeypatch) -> None:
    """reason_purpose now calls verified_generate internally; test via route monkeypatch."""
    import aos_core.services.verifier as verifier_mod
    from aos_core.services.llm_router import RouteResult, Tier

    files = [{"path": "app.py", "text": "print('hi')"}]
    det_settings = types.SimpleNamespace(llm_provider="deterministic")

    # Deterministic tier is gated OUT — verified_generate short-circuits → "".
    def _det_route(task_class, sensitivity, s):
        return RouteResult(tier=Tier.DETERMINISTIC, provider=DeterministicProvider(), reason="test")

    monkeypatch.setattr(verifier_mod, "route", _det_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)
    assert reason_purpose(_RICH_README, files, det_settings) == ""

    # A real (FREE_HOSTED) provider returning a canned purpose yields that exact sentence.
    good = _FakeReasonedProvider("Repo X is a tool useful for Y.")

    def _real_route(task_class, sensitivity, s):
        return RouteResult(tier=Tier.FREE_HOSTED, provider=good, reason="test")

    monkeypatch.setattr(verifier_mod, "route", _real_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)  # skip verify pass
    assert reason_purpose(_RICH_README, files, det_settings) == "Repo X is a tool useful for Y."
    assert good.calls  # the real-provider path actually ran

    # Empty / garbled / purpose-less real output → "" (no fabrication).
    for bad_text in ("", "not json at all", '{"other": "x"}', '{"purpose": "   "}'):
        garbled = _FakeGarbledProvider(bad_text)
        monkeypatch.setattr(verifier_mod, "route", lambda tc, s, st, _p=garbled: RouteResult(tier=Tier.FREE_HOSTED, provider=_p, reason="test"))
        assert reason_purpose(_RICH_README, files, det_settings) == ""


def _patch_route_free_hosted(monkeypatch, provider) -> None:
    """Patch both the verifier and distillation modules to route to a fake FREE_HOSTED provider.

    Two patches are required:
    - ``verifier_mod.route``: controls which provider ``verified_generate`` uses internally.
    - ``distillation_mod.route``: controls the ``real`` flag in ``distill_repository`` so the
      reasoned branch is entered (Tier != DETERMINISTIC).
    ``verifier_mod._available`` is set to ``False`` so the Claude adversarial pass is skipped
    (the fake's output is accepted as-is; end-to-end refutation is tested in test_verifier.py).
    """
    import aos_core.services.distillation as distillation_mod
    import aos_core.services.verifier as verifier_mod
    from aos_core.services.llm_router import RouteResult, Tier

    fake_route = lambda tc, sens, s: RouteResult(  # noqa: E731
        tier=Tier.FREE_HOSTED, provider=provider, reason="test"
    )
    monkeypatch.setattr(verifier_mod, "route", fake_route)
    monkeypatch.setattr(distillation_mod, "route", fake_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)
    # No rotation pool in-process: the capability extractor falls back to the routed fake
    # (deterministic regardless of any GROQ_/GEMINI_ keys in the ambient environment).
    monkeypatch.setattr(distillation_mod, "free_pool_provider", lambda: None)


def test_distill_reasoned_provider_sets_reasoned_purpose_and_state(client, tmp_path, monkeypatch) -> None:
    """verified_generate production path: a FREE_HOSTED fake returns a reasoned purpose."""
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README
    )
    _seed_dna(tmp_path, repo_id)

    provider = _FakeReasonedProvider()
    _patch_route_free_hosted(monkeypatch, provider)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(
            session, repository_id=repo_id, knowledge_root=tmp_path
        )
        assert page.validation_state == "reasoned"
    finally:
        session.close()

    # The production verified_generate path invoked the fake provider.
    assert provider.calls
    # DNA.purpose IS the reasoned line, not the deterministic floor summary.
    purpose = _dna_purpose(tmp_path, repo_id)
    assert purpose == _REASONED_PURPOSE
    assert not purpose.startswith("A reusable library for building command-line widgets")

    # Single source of truth: the rendered page summary reflects the reasoned line.
    text = (tmp_path / page.vault_path).read_text(encoding="utf-8")
    assert _REASONED_PURPOSE in text


def test_distill_deterministic_provider_keeps_floor_and_derived(client, tmp_path, monkeypatch) -> None:
    """DETERMINISTIC route: verified_generate short-circuits; floor summary kept.

    No monkeypatching of route needed: ``get_settings().llm_provider`` defaults to
    ``"deterministic"`` in the test environment, so ``route()`` returns DETERMINISTIC
    already, and ``real`` is False. The test confirms this inherited CI default holds.
    """
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README
    )
    _seed_dna(tmp_path, repo_id)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(
            session, repository_id=repo_id, knowledge_root=tmp_path
        )
        assert page.validation_state == "derived"
    finally:
        session.close()

    # DNA.purpose is the deterministic floor summary (hermetic, no live model).
    purpose = _dna_purpose(tmp_path, repo_id)
    assert purpose.startswith("A reusable library for building command-line widgets")


def test_distill_garbled_reasoned_output_falls_back_to_floor(client, tmp_path, monkeypatch) -> None:
    """FREE_HOSTED fake returns garbled JSON: verified_generate path runs but yields no purpose."""
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README
    )
    _seed_dna(tmp_path, repo_id)

    # A real (non-deterministic) provider whose output has no usable purpose.
    provider = _FakeGarbledProvider('{"purpose": ""}')
    _patch_route_free_hosted(monkeypatch, provider)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(
            session, repository_id=repo_id, knowledge_root=tmp_path
        )
        assert page.validation_state == "derived"
    finally:
        session.close()

    assert provider.calls  # the production path ran, but produced no usable purpose
    purpose = _dna_purpose(tmp_path, repo_id)
    # No fabrication: the deterministic floor summary is preserved.
    assert purpose.startswith("A reusable library for building command-line widgets")


# --- AOS-LLM-ROUTE-COV: distillation service uses routed_provider ---


def _route_settings(**over):
    """Minimal hermetic settings for router-selection assertions."""
    base = dict(
        llm_base_url="http://localhost:11434/v1",
        llm_model="qwen2.5-coder:7b",
        llm_api_key="",
        llm_free_base_url="https://api.groq.com/openai/v1",
        llm_free_model="llama-3.3-70b-versatile",
        llm_free_api_key="gsk_test",
        llm_claude_enabled=False,
    )
    base.update(over)
    return types.SimpleNamespace(**base)


def test_distillation_routes_to_free_tier_when_local_absent(monkeypatch):
    """When LOCAL is unconfigured and a free key exists, distillation picks FREE_HOSTED."""
    import aos_core.services.llm_router as router_mod

    # No rotation pool (slice 3) so the single-key path is exercised.
    monkeypatch.setattr(router_mod, "build_free_pool", lambda: [])
    monkeypatch.setattr(router_mod, "free_pool_provider", lambda: None)

    from aos_core.services.llm_router import Sensitivity, routed_provider

    s = _route_settings(llm_base_url="", llm_model="")
    provider = routed_provider("distillation", Sensitivity.PUBLIC, s)
    assert isinstance(provider, OpenAICompatibleProvider)


def test_distillation_falls_back_deterministic_when_nothing_configured(monkeypatch):
    """With no tier configured, distillation falls back to deterministic (hermetic CI)."""
    import aos_core.services.llm_router as router_mod

    monkeypatch.setattr(router_mod, "build_free_pool", lambda: [])
    monkeypatch.setattr(router_mod, "free_pool_provider", lambda: None)

    from aos_core.services.llm_router import Sensitivity, routed_provider

    s = _route_settings(llm_base_url="", llm_model="", llm_free_api_key="")
    provider = routed_provider("distillation", Sensitivity.PUBLIC, s)
    assert isinstance(provider, DeterministicProvider)
    # is_real_provider check in distill_repository must still read "deterministic"
    assert getattr(provider, "name", "") == "deterministic"


def test_distillation_wraps_in_instrumented_when_sink_supplied(monkeypatch):
    """With a FREE tier configured + sink, routed_provider wraps in InstrumentedProvider."""
    import aos_core.services.llm_router as router_mod

    monkeypatch.setattr(router_mod, "build_free_pool", lambda: [])
    monkeypatch.setattr(router_mod, "free_pool_provider", lambda: None)

    from aos_core.services.llm_router import Sensitivity, routed_provider

    s = _route_settings(llm_base_url="", llm_model="")
    sink_calls: list = []
    provider = routed_provider("distillation", Sensitivity.PUBLIC, s, sink=lambda **kw: sink_calls.append(kw))
    assert isinstance(provider, InstrumentedProvider)
    assert isinstance(provider.inner, OpenAICompatibleProvider)


# --- AOS-DISTILL-005: bounded reason prompt + failure logging (task #50) ------


def test_bounded_reason_body_truncates_oversized_input() -> None:
    """_bounded_reason_body never returns more than budget chars for large input."""
    huge_readme = "R" * 100_000
    large_files = [
        {"path": f"file{i}.py", "text": "x" * 10_000}
        for i in range(5)
    ]
    body = _bounded_reason_body(huge_readme, large_files)
    assert len(body) <= _REASON_PROMPT_CHAR_BUDGET


def test_bounded_reason_body_small_input_is_identical_to_direct_assembly() -> None:
    """When input fits the budget, the result is identical to a direct assembly."""
    readme = "A short README."
    files = [
        {"path": "main.py", "text": "def main(): pass"},
        {"path": "util.py", "text": "def helper(): pass"},
    ]
    body = _bounded_reason_body(readme, files)

    # Direct assembly: same structure the prompt builders used to produce inline.
    direct_parts = ["## README\n" + readme]
    blocks = "\n\n".join(f"### {f['path']}\n{f['text']}" for f in files)
    direct_parts.append("## Source\n" + blocks)
    direct = "\n\n".join(direct_parts)

    assert body == direct


def test_reason_purpose_deterministic_returns_empty_no_call() -> None:
    """DETERMINISTIC route: reason_purpose returns '' without invoking any provider."""
    import aos_core.services.verifier as verifier_mod
    from aos_core.services.llm_router import RouteResult, Tier
    from aos_core.llm import DeterministicProvider

    files = [{"path": "app.py", "text": "print('hi')"}]
    det_settings = types.SimpleNamespace(llm_provider="deterministic")

    def _det_route(task_class, sensitivity, s):
        return RouteResult(tier=Tier.DETERMINISTIC, provider=DeterministicProvider(), reason="test")

    monkeypatch_holder: dict = {}

    class _MP:
        def setattr(self, obj, name, val):
            monkeypatch_holder[(id(obj), name)] = getattr(obj, name)
            setattr(obj, name, val)

    # Use a simple manual patch/restore since this is a non-fixture test.
    orig_route = verifier_mod.route
    orig_avail = verifier_mod._available
    try:
        verifier_mod.route = _det_route
        verifier_mod._available = lambda t, s: False
        result = reason_purpose(_RICH_README, files, det_settings)
    finally:
        verifier_mod.route = orig_route
        verifier_mod._available = orig_avail

    assert result == ""


def test_reason_purpose_logs_warning_when_provider_raises(monkeypatch, caplog) -> None:
    """When the reasoned call raises, reason_purpose logs a warning and returns ''."""
    import aos_core.services.verifier as verifier_mod
    from aos_core.services.llm_router import RouteResult, Tier

    class _BoomProvider:
        name = "boom"

        def generate(self, *, system: str, prompt: str, max_tokens: int = 1024):
            raise RuntimeError("HTTP 413 Request too large")

    boom = _BoomProvider()

    def fake_route(tc, sens, s):
        return RouteResult(tier=Tier.FREE_HOSTED, provider=boom, reason="test")

    monkeypatch.setattr(verifier_mod, "route", fake_route)
    monkeypatch.setattr(verifier_mod, "_available", lambda t, s: False)

    files = [{"path": "main.py", "text": "def main(): pass"}]
    det_settings = types.SimpleNamespace(llm_provider="deterministic")

    with caplog.at_level(logging.WARNING, logger="aos_core.services.distillation"):
        result = reason_purpose(_RICH_README, files, det_settings)

    assert result == ""
    assert any(
        "distillation reasoned tier failed" in record.message
        for record in caplog.records
    )


# --- RFC-0013 Slice 1: capability extraction ----------------------------------
#
# reason_over_source evolves from a thin ``reusable: [str]`` narrative array to a
# first-class ``capabilities: [{name, description, provenance}]`` list — the concrete
# reusable components a DIFFERENT project could borrow, each named and tied to its
# file(s). REASONED TIER ONLY: the deterministic floor fabricates nothing (capabilities
# stays ``[]`` → the section is absent → today's hermetic behaviour is unchanged).

_CAPABILITY_JSON = json.dumps(
    {
        "built_for": "A toolkit for composing terminal widgets.",
        "how_it_works": "Widgets compose over a shared render loop.",
        "capabilities": [
            {
                "name": "widget render loop",
                "description": "reusable draw/update loop for TUIs",
                "provenance": ["core.py"],
            },
            {
                "name": "layout solver",
                "description": "flexbox-like layout engine",
                "provenance": ["layout.py", "core.py"],
            },
        ],
        "provenance": ["core.py", "layout.py"],
    }
)


def _digest(known: set[str], *, full=None) -> dict:
    """A minimal build_repo_digest-shaped payload for reason_over_source unit tests."""
    return {
        "digest": "\n".join(f"- {p} [module]: doc; symbols: sym" for p in sorted(known)),
        "full_modules": full or [],
        "known_files": set(known),
        "known_symbols": {"sym"},
    }


def _route_capability_extraction(monkeypatch, provider, *, pool=None, tier=None) -> None:
    """Route reason_over_source's capability call to a fake provider (distillation-module route)."""
    import aos_core.services.distillation as distillation_mod
    from aos_core.services.llm_router import RouteResult, Tier

    resolved = tier or Tier.FREE_HOSTED
    monkeypatch.setattr(
        distillation_mod,
        "route",
        lambda tc, sens, s: RouteResult(tier=resolved, provider=provider, reason="test"),
    )
    monkeypatch.setattr(distillation_mod, "free_pool_provider", lambda: pool)


class _SequenceProvider:
    """A fake rotation pool: returns the next canned text per call (tests retry-on-empty)."""

    name = "rotating"

    def __init__(self, texts: list[str]) -> None:
        self._texts = texts
        self.calls = 0

    def __len__(self) -> int:
        return len(self._texts)

    def generate(self, *, system: str, prompt: str, max_tokens: int = 1024, response_format=None):
        text = self._texts[min(self.calls, len(self._texts) - 1)]
        self.calls += 1
        return SimpleNamespace(text=text, provider=self.name, model=None, finish_reason="stop")


def test_reason_over_source_deterministic_emits_no_capabilities(monkeypatch) -> None:
    """DETERMINISTIC route: reason_over_source returns {} — no call, no capabilities."""
    import aos_core.services.distillation as distillation_mod
    from aos_core.services.llm_router import RouteResult, Tier

    monkeypatch.setattr(
        distillation_mod,
        "route",
        lambda tc, sens, s: RouteResult(tier=Tier.DETERMINISTIC, provider=DeterministicProvider(), reason="test"),
    )
    assert reason_over_source(_digest({"core.py"}), types.SimpleNamespace(llm_provider="deterministic")) == {}


def test_reason_over_source_parses_first_class_capabilities(monkeypatch) -> None:
    """A real provider returning capability objects (citing known files) → parsed + kept."""
    provider = _FakeGarbledProvider(_CAPABILITY_JSON)
    _route_capability_extraction(monkeypatch, provider)

    narrative = reason_over_source(_digest({"core.py", "layout.py"}), types.SimpleNamespace(llm_provider="x"))

    assert provider.calls  # the reasoned path actually ran
    # The system prompt explicitly asks for reusable capabilities grounded in provided files.
    assert "capabilit" in provider.calls[0]["system"].lower()

    caps = narrative["capabilities"]
    assert [c["name"] for c in caps] == ["widget render loop", "layout solver"]
    assert caps[0]["description"] == "reusable draw/update loop for TUIs"
    assert caps[0]["provenance"] == ["core.py"]
    # The legacy bare-string ``reusable`` key is gone from the narrative contract.
    assert "reusable" not in narrative


def test_reason_over_source_drops_capabilities_citing_unknown_files(monkeypatch) -> None:
    """Deterministic cite-must-exist: a capability citing a file the digest never showed is dropped."""
    payload = json.dumps(
        {
            "built_for": "x",
            "how_it_works": "",
            "capabilities": [
                {"name": "real", "description": "d", "provenance": ["core.py"]},
                {"name": "ghost", "description": "hallucinated", "provenance": ["does/not/exist.py"]},
            ],
        }
    )
    provider = _FakeGarbledProvider(payload)
    _route_capability_extraction(monkeypatch, provider)

    narrative = reason_over_source(_digest({"core.py"}), types.SimpleNamespace(llm_provider="x"))
    assert [c["name"] for c in narrative["capabilities"]] == ["real"]  # ghost dropped structurally


def test_reason_over_source_marks_incomplete_when_nothing_grounded(monkeypatch) -> None:
    """Real tier ran but no capability grounds to a real file → extraction_incomplete, never silent."""
    payload = json.dumps(
        {"built_for": "x", "how_it_works": "y", "capabilities": [{"name": "ghost", "provenance": ["nope.py"]}]}
    )
    provider = _FakeGarbledProvider(payload)
    _route_capability_extraction(monkeypatch, provider)

    narrative = reason_over_source(_digest({"core.py"}), types.SimpleNamespace(llm_provider="x"))
    assert narrative["capabilities"] == []
    assert narrative["extraction_incomplete"] is True


def test_reason_over_source_retries_across_pool_until_grounded(monkeypatch) -> None:
    """Retry-on-empty: an empty/ungrounded member advances to the next free-pool provider."""
    empty = json.dumps({"capabilities": []})
    good = json.dumps({"capabilities": [{"name": "real", "description": "d", "provenance": ["core.py"]}]})
    seq = _SequenceProvider([empty, good])
    # route tier is real (FREE_HOSTED); the pool (seq) is what actually serves + rotates.
    _route_capability_extraction(monkeypatch, DeterministicProvider(), pool=seq)

    narrative = reason_over_source(_digest({"core.py"}), types.SimpleNamespace(llm_provider="x"))
    assert [c["name"] for c in narrative["capabilities"]] == ["real"]
    assert seq.calls == 2  # first (empty) member retried onto the second (grounded)


def test_render_repository_markdown_renders_reusable_capabilities() -> None:
    """render emits a '## Reusable capabilities' section, each capability citing its file(s)."""
    distillation = extract_repo_knowledge(_RICH_README)
    distillation["narrative"] = {
        "built_for": "",
        "how_it_works": "",
        "capabilities": [
            {
                "name": "LLM provider-routing abstraction",
                "description": "swap providers by tier",
                "provenance": ["router.py"],
            }
        ],
        "provenance": ["router.py"],
    }
    md = render_repository_markdown(distillation)
    assert "## Reusable capabilities" in md
    assert "LLM provider-routing abstraction" in md
    assert "swap providers by tier" in md
    assert "`router.py`" in md


def test_render_repository_markdown_no_narrative_has_no_capabilities_section() -> None:
    """Deterministic floor (no narrative) renders no capabilities section — unchanged behaviour."""
    md = render_repository_markdown(extract_repo_knowledge(_RICH_README))
    assert "## Reusable capabilities" not in md


class _FakeCapabilityProvider:
    """Fake real provider: capability JSON for the source-reasoning prompt, purpose JSON otherwise.

    Distinguishes the two distillation system prompts by the presence of 'capabilit' in the
    system text (reason_over_source asks for capabilities; reason_purpose asks for a purpose).
    """

    name = "claude_code"

    def __init__(self) -> None:
        self.calls: list[dict] = []

    def generate(self, *, system: str, prompt: str, max_tokens: int = 1024):
        self.calls.append({"system": system, "prompt": prompt})
        if "capabilit" in system.lower():
            text = _CAPABILITY_JSON
        else:
            text = json.dumps({"purpose": _REASONED_PURPOSE})
        return SimpleNamespace(text=text, provider=self.name, model=None, finish_reason="stop")


def test_distill_reasoned_provider_renders_capabilities_section(client, tmp_path, monkeypatch) -> None:
    """End-to-end: a reasoned distill writes a '## Reusable capabilities' section into the vault page."""
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_code_repo(client, project_id, name="Code Repo", local_path="code-repo")

    provider = _FakeCapabilityProvider()
    _patch_route_free_hosted(monkeypatch, provider)

    session = _same_file_session(tmp_path)
    try:
        page = distill_repository(session, repository_id=repo_id, knowledge_root=tmp_path)
        assert page.validation_state == "reasoned"
    finally:
        session.close()

    text = (tmp_path / page.vault_path).read_text(encoding="utf-8")
    assert "## Reusable capabilities" in text
    assert "widget render loop" in text
    assert "`core.py`" in text


# --- RFC-0013 Slice 1 (digest pivot): whole-repo digest + cite-must-exist filter ---
#
# The reality gate showed "pick 5 full files" starves capability coverage and invites
# import-name hallucination. The pivot feeds the model a whole-repo SYMBOL DIGEST (every
# source file's role + top-level symbols + docstring) plus a few full high-signal modules,
# and then structurally drops any capability whose provenance is not a file the digest
# actually saw (deterministic anti-hallucination — Article XII).


def test_build_repo_digest_maps_whole_repo_and_excludes_noise(client, tmp_path) -> None:
    local_path = _write_repo(
        settings.repository_root,
        {
            "pkg/__init__.py": "",  # empty marker — carries no capability content
            "pkg/service.py": '"""Approval queue service."""\n\ndef enqueue():\n    return 1\n\n\nclass Queue:\n    pass\n',
            "packages/core/core/services/llm_router.py": '"""LLM provider routing."""\n\ndef route(task):\n    return "tier"\n\n\ndef fallback():\n    return None\n',
            "tests/test_service.py": "def test_enqueue():\n    assert True\n" * 10,  # noise
        },
    )
    digest = build_repo_digest(SimpleNamespace(local_path=local_path))

    text = digest["digest"]
    known = digest["known_files"]
    # Whole-repo map: both real modules appear with their symbols; the crown jewel is present.
    assert "pkg/service.py" in text
    assert "packages/core/core/services/llm_router.py" in text
    assert "route" in text and "enqueue" in text
    # Known-files set backs the cite filter and covers the real modules.
    assert "pkg/service.py" in known
    assert "packages/core/core/services/llm_router.py" in known
    # Noise is excluded: empty markers and test files never enter the digest/known set.
    assert "__init__.py" not in text
    assert not any(p.startswith("tests/") for p in known)
    # A few full modules are carried verbatim for depth (crown jewels), each a known file.
    full_paths = {m["path"] for m in digest["full_modules"]}
    assert full_paths
    assert full_paths <= known
    assert all("text" in m and m["text"] for m in digest["full_modules"])


def test_build_repo_digest_tolerant_of_missing_repo(client, tmp_path) -> None:
    digest = build_repo_digest(SimpleNamespace(local_path="does-not-exist"))
    assert digest["digest"] == ""
    assert digest["known_files"] == set()
    assert digest["full_modules"] == []


def test_drop_uncited_capabilities_removes_hallucinated_and_uncited() -> None:
    known = {"pkg/service.py", "packages/core/core/services/llm_router.py"}
    caps = [
        {"name": "Approval queue", "description": "x", "provenance": ["pkg/service.py"]},
        {"name": "LLM routing", "description": "y", "provenance": ["services/llm_router.py"]},  # basename match
        {"name": "SOP via LLM", "description": "hallucinated", "provenance": ["app/sop/llm.py"]},  # not in repo
        {"name": "Uncited", "description": "no provenance", "provenance": []},  # cannot verify
    ]
    kept = _drop_uncited_capabilities(caps, known)
    names = [c["name"] for c in kept]

    assert "Approval queue" in names  # exact provenance match survives
    assert "LLM routing" in names  # basename/suffix match against a known file survives
    assert "SOP via LLM" not in names  # cites a file the repo does not contain → dropped
    assert "Uncited" not in names  # no citation → cannot ground → dropped


# --- AOS-REVIEW-002 follow-up (P0-6): distillation egress via the authority envelope ---


def test_distill_records_authorized_egress_envelope(client, tmp_path) -> None:
    from aos_core.models import ActionRequest

    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Env", local_path="env", readme="# Env\n\nhello world")

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text

    session = _same_file_session(tmp_path)
    try:
        ars = session.query(ActionRequest).filter(ActionRequest.action_class == "external_network").all()
        assert len(ars) == 1, "distillation egress creates exactly one authority envelope"
        assert ars[0].execution_state == "executed"
        assert ars[0].target == f"repository:{repo_id}"
    finally:
        session.close()


def test_distill_blocked_when_egress_requires_approval(client, tmp_path, monkeypatch) -> None:
    import aos_core.services.authority_envelope as env
    from aos_core.models import KnowledgePage

    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Gate", local_path="gate", readme="# Gate\n\nhello")

    # A policy that requires approval for egress leaves the envelope pending → 403.
    monkeypatch.setattr(env, "requires_approval", lambda *a, **k: True)
    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 403, resp.text
    detail = resp.json()["detail"]
    assert detail["reason"].startswith("distillation egress")
    assert detail["action_request_id"]

    # The egress was refused before distillation ran — no page written.
    session = _same_file_session(tmp_path)
    try:
        assert session.query(KnowledgePage).filter(KnowledgePage.page_type == "repository").count() == 0
    finally:
        session.close()
