"""API + service tests for repository distillation (AOS-DISTILL-001 / RFC-0008).

Repo content → Knowledge: a scanned repo's README is distilled by a deterministic,
provenance-tagged extractor into ``knowledge/wiki/repositories/<slug>.md`` (repo
vault = source of truth) and projected as a re-syncable ``KnowledgePage``
(``page_type="repository"``). Distillation is idempotent and fails gracefully
(409, not 500) on a non-writable vault without mutating state; a README-less repo
yields a minimal page and never raises.

CRITICAL: every I/O test points ``settings.repository_root`` (via the ``client``
fixture) AND ``settings.knowledge_root`` at ``tmp_path`` — distillation never
reads the real ``repositories/`` nor writes the real ``knowledge/`` vault.
"""

from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from aos_core.models import KnowledgePage, RepositoryDNA
from aos_core.services.distillation import (
    _repo_slug,
    extract_repo_knowledge,
    render_repository_markdown,
)

from app.main import settings

UNKNOWN_ID = "00000000-0000-0000-0000-000000000000"

_RICH_README = """\
# Widget Toolkit

A reusable library for building command-line widgets with a small footprint.

## Installation

```bash
pip install widget-toolkit
```

## Usage

```python
from widget import Widget
```

## Contributing

PRs welcome.
"""

_FREE_LLM_README = """\
<!---
WARNING: DO NOT EDIT THIS FILE DIRECTLY.
--->
# Free LLM API resources

This lists various services that provide free access or credits towards API-based LLM usage.

> [!NOTE]
> Please don't abuse these services.

## Free Providers

### OpenRouter

Free tier available.

## Providers with trial credits

### Fireworks

Trial credits on signup.
"""


def _same_file_session(tmp_path):
    engine = create_engine(
        f"sqlite:///{tmp_path / 'test.db'}",
        connect_args={"check_same_thread": False, "timeout": 30},
        pool_pre_ping=True,
    )
    return sessionmaker(bind=engine, autoflush=False, autocommit=False, expire_on_commit=False)()


def _project(client) -> str:
    return client.post("/projects", json={"name": "Distill", "slug": "distill"}).json()["id"]


def _register_repo(client, project_id: str, *, name: str, local_path: str, readme: str | None) -> str:
    """Create a repo dir under the (tmp) repository_root and register it."""
    repo_dir = settings.repository_root / local_path
    repo_dir.mkdir(parents=True, exist_ok=True)
    if readme is not None:
        (repo_dir / "README.md").write_text(readme, encoding="utf-8")
    resp = client.post(
        f"/projects/{project_id}/repositories",
        json={"name": name, "local_path": local_path},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()["id"]


# --- extract_repo_knowledge (pure) -----------------------------------------


def test_extract_repo_knowledge_from_readme() -> None:
    result = extract_repo_knowledge(_RICH_README)

    assert result["title"] == "Widget Toolkit"
    assert result["summary"].startswith("A reusable library for building command-line widgets")
    # Section headings become key points.
    assert any(kp.startswith("Installation") for kp in result["key_points"])
    assert any(kp.startswith("Usage") for kp in result["key_points"])
    # Fenced-code languages are surfaced as technologies.
    assert "python" in [t.lower() for t in result["technologies"]]
    assert "bash" in [t.lower() for t in result["technologies"]]
    # useful_for picks up the "library" / "command-line" signals.
    assert result["useful_for"]
    # Every provenance item cites its source; at least one cites the README.
    assert result["provenance"]
    assert all("source" in entry and "item" in entry for entry in result["provenance"])
    assert any("README.md" in entry["source"] for entry in result["provenance"])


def test_extract_free_llm_style_catalog_names_the_catalog() -> None:
    result = extract_repo_knowledge(_FREE_LLM_README)

    # Title/summary name WHAT IT IS (a catalog), not a structural fingerprint.
    assert result["title"] == "Free LLM API resources"
    assert result["summary"].startswith("This lists various services that provide free access")
    # The catalog / curated-list signal is surfaced under useful_for.
    assert any("catalog" in phrase.lower() or "list" in phrase.lower() for phrase in result["useful_for"])
    # HTML comment + blockquote are not mistaken for the summary.
    assert "DO NOT EDIT" not in result["summary"]
    assert "abuse" not in result["summary"]


def test_extract_empty_readme_is_minimal_and_never_raises() -> None:
    result = extract_repo_knowledge("   \n\n")
    assert result["title"] == "Untitled repository"
    assert "No README content" in result["summary"]
    assert result["key_points"] == []
    assert result["technologies"] == []


def test_render_repository_markdown_has_all_sections() -> None:
    md = render_repository_markdown(extract_repo_knowledge(_RICH_README))
    assert "# Widget Toolkit" in md
    assert "## Summary" in md
    assert "## What it is / useful for" in md
    assert "## Key points" in md
    assert "## Technologies" in md
    assert "## Provenance" in md


def test_repo_slug() -> None:
    assert _repo_slug("free-llm-api-resources") == "free-llm-api-resources"
    assert _repo_slug("My Cool Repo!") == "my-cool-repo"
    assert _repo_slug("") == "repository"


# --- distill_repository (I/O + KnowledgePage projection) --------------------


def test_distill_writes_page_and_sets_dna_purpose(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(
        client, project_id, name="Free LLM API Resources", local_path="free-llm", readme=_FREE_LLM_README
    )

    # Seed a DNA row so distillation can enrich technologies + stamp purpose.
    session = _same_file_session(tmp_path)
    try:
        session.add(
            RepositoryDNA(
                repository_id=repo_id,
                package_managers=["pip"],
                scan_summary={"summary": {"language_classes": {"Python": "source", "Markdown": "docs"}}},
            )
        )
        session.commit()
    finally:
        session.close()

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()
    assert page["page_type"] == "repository"
    assert page["validation_state"] == "derived"
    assert page["vault_path"] == "wiki/repositories/free-llm-api-resources.md"
    assert page["title"] == "Free LLM API resources"
    ref_types = {ref["type"] for ref in page["source_refs"]}
    assert "repository" in ref_types and "vault_file" in ref_types

    written = tmp_path / page["vault_path"]
    assert written.is_file()
    text = written.read_text(encoding="utf-8")
    assert "# Free LLM API resources" in text
    assert "This lists various services" in text
    assert "pip" in text  # DNA package manager surfaced as a technology
    assert "Python" in text  # DNA source language surfaced

    # DNA.purpose stamped with the distilled summary.
    session = _same_file_session(tmp_path)
    try:
        dna = session.query(RepositoryDNA).filter(RepositoryDNA.repository_id == repo_id).one()
        assert dna.purpose.startswith("This lists various services")
    finally:
        session.close()

    # Projected page is queryable and typed.
    pages = client.get("/knowledge/pages", params={"page_type": "repository"}).json()
    assert page["id"] in [p["id"] for p in pages]


def test_distill_is_idempotent(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README)

    first = client.post(f"/repositories/{repo_id}/distill")
    second = client.post(f"/repositories/{repo_id}/distill")
    assert first.status_code == 200 and second.status_code == 200, second.text
    assert first.json()["vault_path"] == second.json()["vault_path"]
    assert first.json()["id"] == second.json()["id"]

    # One file, one page.
    matches = list((tmp_path / "wiki" / "repositories").glob("*.md"))
    assert len(matches) == 1
    session = _same_file_session(tmp_path)
    try:
        assert (
            session.query(KnowledgePage)
            .filter(KnowledgePage.vault_path == "wiki/repositories/widget-toolkit.md")
            .count()
            == 1
        )
    finally:
        session.close()


def test_distill_non_writable_vault_is_409_without_mutating_state(client, tmp_path) -> None:
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Widget Toolkit", local_path="widget", readme=_RICH_README)

    # Point knowledge_root at a *file*, so mkdir under it raises OSError.
    bad_root = tmp_path / "not-a-dir"
    bad_root.write_text("x", encoding="utf-8")
    settings.knowledge_root = bad_root

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 409, resp.text
    assert "local-first" in resp.json()["detail"].lower()

    # No KnowledgePage was created (state untouched).
    session = _same_file_session(tmp_path)
    try:
        assert session.query(KnowledgePage).filter(KnowledgePage.page_type == "repository").count() == 0
    finally:
        session.close()


def test_distill_readme_less_repo_is_minimal_and_no_raise(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    project_id = _project(client)
    repo_id = _register_repo(client, project_id, name="Empty Repo", local_path="empty", readme=None)

    resp = client.post(f"/repositories/{repo_id}/distill")
    assert resp.status_code == 200, resp.text
    page = resp.json()
    assert page["page_type"] == "repository"
    # No README → title falls back to the registered repo name.
    assert page["title"] == "Empty Repo"

    text = (tmp_path / page["vault_path"]).read_text(encoding="utf-8")
    assert "# Empty Repo" in text
    assert "No README content" in text


def test_distill_missing_repository_is_404(client, tmp_path) -> None:
    settings.knowledge_root = tmp_path
    assert client.post(f"/repositories/{UNKNOWN_ID}/distill").status_code == 404
