"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-05 18:23:28.676416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import aos_core.models  # provides the GUID / JSONField TypeDecorators referenced below


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=128), nullable=False),
    sa.Column('capabilities', aos_core.models.JSONField(), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('engines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engine_type', sa.String(length=128), nullable=False),
    sa.Column('capabilities', aos_core.models.JSONField(), nullable=False),
    sa.Column('inputs', aos_core.models.JSONField(), nullable=False),
    sa.Column('outputs', aos_core.models.JSONField(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_engines_status'), 'engines', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_projects_slug')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('authority_grants',
    sa.Column('project_id', aos_core.models.GUID(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('capability', sa.String(length=255), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('authority_level', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approver', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_grants_project_id'), 'authority_grants', ['project_id'], unique=False)
    op.create_index(op.f('ix_authority_grants_status'), 'authority_grants', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('alternatives', aos_core.models.JSONField(), nullable=False),
    sa.Column('tradeoffs', aos_core.models.JSONField(), nullable=False),
    sa.Column('consequences', aos_core.models.JSONField(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_table('knowledge_pages',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('vault_path', sa.Text(), nullable=False),
    sa.Column('page_type', sa.String(length=128), nullable=False),
    sa.Column('validation_state', sa.String(length=128), nullable=False),
    sa.Column('source_refs', aos_core.models.JSONField(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_pages_project_id'), 'knowledge_pages', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_pages_status'), 'knowledge_pages', ['status'], unique=False)
    op.create_table('nightly_digests',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('digest_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changes', aos_core.models.JSONField(), nullable=False),
    sa.Column('recommendations', aos_core.models.JSONField(), nullable=False),
    sa.Column('repeated_tasks', aos_core.models.JSONField(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nightly_digests_project_id'), 'nightly_digests', ['project_id'], unique=False)
    op.create_index(op.f('ix_nightly_digests_status'), 'nightly_digests', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('alternatives', aos_core.models.JSONField(), nullable=False),
    sa.Column('pros', aos_core.models.JSONField(), nullable=False),
    sa.Column('cons', aos_core.models.JSONField(), nullable=False),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('effort', sa.String(length=128), nullable=True),
    sa.Column('dependencies', aos_core.models.JSONField(), nullable=False),
    sa.Column('acceptance_criteria', aos_core.models.JSONField(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_project_id'), 'recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('repositories',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('remote_url', sa.Text(), nullable=True),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_project_id'), 'repositories', ['project_id'], unique=False)
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_table('research_notes',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sources', aos_core.models.JSONField(), nullable=False),
    sa.Column('findings', aos_core.models.JSONField(), nullable=False),
    sa.Column('freshness', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_project_id'), 'research_notes', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_notes_status'), 'research_notes', ['status'], unique=False)
    op.create_table('approval_records',
    sa.Column('project_id', aos_core.models.GUID(), nullable=True),
    sa.Column('authority_grant_id', aos_core.models.GUID(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('agent', sa.String(length=128), nullable=True),
    sa.Column('tool', sa.String(length=128), nullable=True),
    sa.Column('action_level', sa.Integer(), nullable=False),
    sa.Column('requested_capability', sa.String(length=255), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=64), nullable=False),
    sa.Column('output', aos_core.models.JSONField(), nullable=True),
    sa.Column('rollback_notes', sa.Text(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['authority_grant_id'], ['authority_grants.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_records_authority_grant_id'), 'approval_records', ['authority_grant_id'], unique=False)
    op.create_index(op.f('ix_approval_records_project_id'), 'approval_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_approval_records_status'), 'approval_records', ['status'], unique=False)
    op.create_table('architecture_nodes',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('parent_id', aos_core.models.GUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('risks', aos_core.models.JSONField(), nullable=False),
    sa.Column('related_decision_ids', aos_core.models.JSONField(), nullable=False),
    sa.Column('manual_correction', sa.Text(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['architecture_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_nodes_parent_id'), 'architecture_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_project_id'), 'architecture_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_repository_id'), 'architecture_nodes', ['repository_id'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_status'), 'architecture_nodes', ['status'], unique=False)
    op.create_table('benchmarks',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('benchmark_type', sa.String(length=128), nullable=True),
    sa.Column('metric', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('environment', aos_core.models.JSONField(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmarks_project_id'), 'benchmarks', ['project_id'], unique=False)
    op.create_index(op.f('ix_benchmarks_repository_id'), 'benchmarks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_benchmarks_status'), 'benchmarks', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('evaluation_type', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('findings', aos_core.models.JSONField(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_project_id'), 'evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_evaluations_repository_id'), 'evaluations', ['repository_id'], unique=False)
    op.create_index(op.f('ix_evaluations_status'), 'evaluations', ['status'], unique=False)
    op.create_table('experiments',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)
    op.create_index(op.f('ix_experiments_repository_id'), 'experiments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', aos_core.models.GUID(), nullable=True),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('job_type', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', aos_core.models.JSONField(), nullable=False),
    sa.Column('result', aos_core.models.JSONField(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_repository_id'), 'jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('repository_dna',
    sa.Column('repository_id', aos_core.models.GUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('maturity', sa.String(length=128), nullable=True),
    sa.Column('language_mix', aos_core.models.JSONField(), nullable=False),
    sa.Column('package_managers', aos_core.models.JSONField(), nullable=False),
    sa.Column('frameworks', aos_core.models.JSONField(), nullable=False),
    sa.Column('runtime_services', aos_core.models.JSONField(), nullable=False),
    sa.Column('deployment_files', aos_core.models.JSONField(), nullable=False),
    sa.Column('risk_flags', aos_core.models.JSONField(), nullable=False),
    sa.Column('scan_summary', aos_core.models.JSONField(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_dna_repository_id'), 'repository_dna', ['repository_id'], unique=True)
    op.create_index(op.f('ix_repository_dna_status'), 'repository_dna', ['status'], unique=False)
    op.create_table('risks',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('likelihood', sa.String(length=64), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_project_id'), 'risks', ['project_id'], unique=False)
    op.create_index(op.f('ix_risks_repository_id'), 'risks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('architecture_edges',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('from_node_id', aos_core.models.GUID(), nullable=False),
    sa.Column('to_node_id', aos_core.models.GUID(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('manual_correction', sa.Text(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['architecture_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['architecture_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_edges_from_node_id'), 'architecture_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_architecture_edges_project_id'), 'architecture_edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_architecture_edges_repository_id'), 'architecture_edges', ['repository_id'], unique=False)
    op.create_index(op.f('ix_architecture_edges_status'), 'architecture_edges', ['status'], unique=False)
    op.create_index(op.f('ix_architecture_edges_to_node_id'), 'architecture_edges', ['to_node_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('repository_id', aos_core.models.GUID(), nullable=True),
    sa.Column('job_id', aos_core.models.GUID(), nullable=True),
    sa.Column('artifact_type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifacts_repository_id'), 'artifacts', ['repository_id'], unique=False)
    op.create_index(op.f('ix_artifacts_status'), 'artifacts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_status'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_repository_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_architecture_edges_to_node_id'), table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_status'), table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_repository_id'), table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_project_id'), table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_from_node_id'), table_name='architecture_edges')
    op.drop_table('architecture_edges')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_repository_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_project_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_repository_dna_status'), table_name='repository_dna')
    op.drop_index(op.f('ix_repository_dna_repository_id'), table_name='repository_dna')
    op.drop_table('repository_dna')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_repository_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_repository_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_evaluations_status'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_repository_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_project_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_benchmarks_status'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_repository_id'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_project_id'), table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_index(op.f('ix_architecture_nodes_status'), table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_repository_id'), table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_project_id'), table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_parent_id'), table_name='architecture_nodes')
    op.drop_table('architecture_nodes')
    op.drop_index(op.f('ix_approval_records_status'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_project_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_authority_grant_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_research_notes_status'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_project_id'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_project_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_project_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_nightly_digests_status'), table_name='nightly_digests')
    op.drop_index(op.f('ix_nightly_digests_project_id'), table_name='nightly_digests')
    op.drop_table('nightly_digests')
    op.drop_index(op.f('ix_knowledge_pages_status'), table_name='knowledge_pages')
    op.drop_index(op.f('ix_knowledge_pages_project_id'), table_name='knowledge_pages')
    op.drop_table('knowledge_pages')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_authority_grants_status'), table_name='authority_grants')
    op.drop_index(op.f('ix_authority_grants_project_id'), table_name='authority_grants')
    op.drop_table('authority_grants')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_engines_status'), table_name='engines')
    op.drop_table('engines')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
