"""council

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-05 22:27:50.148643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import aos_core.models  # provides the GUID / JSONField TypeDecorators referenced below


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('council_reviews',
    sa.Column('project_id', aos_core.models.GUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('agreements', aos_core.models.JSONField(), nullable=False),
    sa.Column('disagreements', aos_core.models.JSONField(), nullable=False),
    sa.Column('unsupported_claims', aos_core.models.JSONField(), nullable=False),
    sa.Column('follow_up', aos_core.models.JSONField(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('job_id', aos_core.models.GUID(), nullable=True),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_council_reviews_job_id'), 'council_reviews', ['job_id'], unique=False)
    op.create_index(op.f('ix_council_reviews_project_id'), 'council_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_council_reviews_status'), 'council_reviews', ['status'], unique=False)
    op.create_table('council_agent_outputs',
    sa.Column('review_id', aos_core.models.GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('agent_type', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings', aos_core.models.JSONField(), nullable=False),
    sa.Column('evidence', aos_core.models.JSONField(), nullable=False),
    sa.Column('concerns', aos_core.models.JSONField(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', aos_core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('metadata', aos_core.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['council_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_council_agent_outputs_review_id'), 'council_agent_outputs', ['review_id'], unique=False)
    op.create_index(op.f('ix_council_agent_outputs_status'), 'council_agent_outputs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_council_agent_outputs_status'), table_name='council_agent_outputs')
    op.drop_index(op.f('ix_council_agent_outputs_review_id'), table_name='council_agent_outputs')
    op.drop_table('council_agent_outputs')
    op.drop_index(op.f('ix_council_reviews_status'), table_name='council_reviews')
    op.drop_index(op.f('ix_council_reviews_project_id'), table_name='council_reviews')
    op.drop_index(op.f('ix_council_reviews_job_id'), table_name='council_reviews')
    op.drop_table('council_reviews')
    # ### end Alembic commands ###
