"""Foundation Intelligence Slice 0 — vocabulary and contracts (RFC-0017).

Pure leaf subpackage: stdlib + pydantic + ``aos_core.sensitivity`` only. No
persistence, no API, no LLM. Re-exports the public surface so later slices
import everything from ``aos_core.foundation`` rather than reaching into
individual modules.
"""
from __future__ import annotations

from .authority import AuthorityDomain, AuthorityLevel, authority_of
from .contracts import (
    Archetype,
    Claim,
    ClaimEvidenceLink,
    ClaimRelationshipEdge,
    ClaimScope,
    CandidateScore,
    CorpusSnapshot,
    Derivation,
    EvidenceConflict,
    EvidenceFragment,
    EvidenceSource,
    EvidenceSourceVersion,
    FoundationBaseline,
    FoundationCandidate,
    FoundationElement,
    FoundationRequirement,
    GenomeSnapshot,
    GenomeTrait,
    Locator,
    OpenQuestion,
    RepositoryRef,
    SelectionStageEvent,
    ValidationTask,
)
from .enums import (
    AnswerType,
    BaselineStatus,
    CandidateStatus,
    ClaimRelationship,
    ClaimStatus,
    ClaimType,
    ConflictStatus,
    ConflictType,
    Criticality,
    DerivationMethod,
    EvaluationCriterion,
    EvidenceRelationship,
    ExtractionMethod,
    FoundationDomain,
    GenomeDimension,
    GenomeStatus,
    IngestionMethod,
    Materiality,
    Polarity,
    Priority,
    QuestionStatus,
    RequirementType,
    Reversibility,
    SelectionRunState,
    SourceOrigin,
    SourceStatus,
    SourceType,
    Stability,
    StateView,
    Strength,
    TraitClassification,
    TruthLayer,
    ValidationStatus,
    ValidationType,
)
from .lifecycle import (
    BASELINE_STATUS_TRANSITIONS,
    CANDIDATE_STATUS_TRANSITIONS,
    CLAIM_STATUS_TRANSITIONS,
    CONFLICT_STATUS_TRANSITIONS,
    GENOME_STATUS_TRANSITIONS,
    SELECTION_RUN_TRANSITIONS,
    VALIDATION_STATUS_TRANSITIONS,
    LifecycleKind,
    can_transition,
    next_states,
)
from .schema_gen import generate_schemas, write_schemas
from .serialization import CONTENT_FIELDS, canonical_bytes, content_hash, set_hash
from .truth import MinterClass, allowed_truth_layers, may_mint

__all__ = [
    # authority
    "AuthorityDomain",
    "AuthorityLevel",
    "authority_of",
    # contracts
    "Archetype",
    "Claim",
    "ClaimEvidenceLink",
    "ClaimRelationshipEdge",
    "ClaimScope",
    "CandidateScore",
    "CorpusSnapshot",
    "Derivation",
    "EvidenceConflict",
    "EvidenceFragment",
    "EvidenceSource",
    "EvidenceSourceVersion",
    "FoundationBaseline",
    "FoundationCandidate",
    "FoundationElement",
    "FoundationRequirement",
    "GenomeSnapshot",
    "GenomeTrait",
    "Locator",
    "OpenQuestion",
    "RepositoryRef",
    "SelectionStageEvent",
    "ValidationTask",
    # enums
    "AnswerType",
    "BaselineStatus",
    "CandidateStatus",
    "ClaimRelationship",
    "ClaimStatus",
    "ClaimType",
    "ConflictStatus",
    "ConflictType",
    "Criticality",
    "DerivationMethod",
    "EvaluationCriterion",
    "EvidenceRelationship",
    "ExtractionMethod",
    "FoundationDomain",
    "GenomeDimension",
    "GenomeStatus",
    "IngestionMethod",
    "Materiality",
    "Polarity",
    "Priority",
    "QuestionStatus",
    "RequirementType",
    "Reversibility",
    "SelectionRunState",
    "SourceOrigin",
    "SourceStatus",
    "SourceType",
    "Stability",
    "StateView",
    "Strength",
    "TraitClassification",
    "TruthLayer",
    "ValidationStatus",
    "ValidationType",
    # lifecycle
    "BASELINE_STATUS_TRANSITIONS",
    "CANDIDATE_STATUS_TRANSITIONS",
    "CLAIM_STATUS_TRANSITIONS",
    "CONFLICT_STATUS_TRANSITIONS",
    "GENOME_STATUS_TRANSITIONS",
    "SELECTION_RUN_TRANSITIONS",
    "VALIDATION_STATUS_TRANSITIONS",
    "LifecycleKind",
    "can_transition",
    "next_states",
    # schema_gen
    "generate_schemas",
    "write_schemas",
    # serialization
    "CONTENT_FIELDS",
    "canonical_bytes",
    "content_hash",
    "set_hash",
    # truth
    "MinterClass",
    "allowed_truth_layers",
    "may_mint",
]
